# Generated by Django 5.1 on 2024-08-25 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('festival_name', models.CharField(db_column='축제명', max_length=50)),
                ('venue', models.CharField(db_column='개최장소', max_length=50)),
                ('start_date', models.DateField(db_column='축제시작일자')),
                ('end_date', models.DateField(db_column='축제종료일자')),
                ('content', models.TextField(db_column='축제내용')),
                ('phone_number', models.CharField(db_column='전화번호', max_length=50)),
                ('website', models.URLField(db_column='홈페이지주소')),
                ('road_address', models.CharField(db_column='소재지도로명주소', max_length=50)),
                ('jibun_address', models.CharField(db_column='소재지지번주소', max_length=50)),
                ('latitude', models.FloatField(db_column='위도')),
                ('longitude', models.FloatField(db_column='경도')),
                ('provider', models.CharField(db_column='제공기관명', max_length=20)),
                ('region', models.CharField(db_column='지역', max_length=20)),
            ],
            options={
                'db_table': 'Pinformation',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('membership_number', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Pboard',
            fields=[
                ('board_number', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_c', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Pboard',
            },
        ),
        migrations.CreateModel(
            name='Pcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kingchobo.pboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Pcomment',
            },
        ),
    ]
