# Generated by Django 5.1 on 2024-08-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingchobo', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='pboard',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
