# Generated by Django 5.1 on 2024-08-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingchobo', '0003_pboard_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pboard',
            name='font_family',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pboard',
            name='font_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
