# Generated by Django 5.1 on 2024-08-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingchobo', '0004_pboard_font_family_pboard_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pboard',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='pboard',
            name='font_size',
        ),
    ]
