# Generated by Django 5.1 on 2024-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingchobo', '0005_remove_pboard_font_family_remove_pboard_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pboard',
            name='font_family',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AddField(
            model_name='pboard',
            name='font_size',
            field=models.CharField(default='12px', max_length=10),
        ),
    ]
