# Generated by Django 5.1 on 2024-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingchobo', '0006_pboard_font_family_pboard_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pboard',
            name='region',
        ),
        migrations.AddField(
            model_name='pboard',
            name='category',
            field=models.CharField(choices=[('recommendation', '추천'), ('chat', '사담'), ('review', '후기'), ('transport', '교통정보'), ('restaurant', '근처 맛집'), ('other', '기타')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='pboard',
            name='font_size',
            field=models.CharField(default='16px', max_length=10),
        ),
    ]
