# Generated by Django 5.1 on 2024-08-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingchobo', '0007_remove_pboard_region_pboard_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pboard',
            name='category',
            field=models.CharField(choices=[('recommendation', '추천'), ('chat', '사담'), ('review', '후기'), ('transport', '교통정보'), ('restaurant', '근처 맛집'), ('other', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pboard',
            name='font_family',
            field=models.CharField(choices=[('Noto Sans KR', 'Noto Sans KR'), ('Nanum Gothic', 'Nanum Gothic'), ('Orbit', 'Orbit'), ('Dongle', 'Dongle'), ('Do Hyeon', 'Do Hyeon')], default='Noto Sans KR', max_length=50),
        ),
        migrations.AlterField(
            model_name='pboard',
            name='font_size',
            field=models.CharField(choices=[('16px', '16px'), ('18px', '18px'), ('20px', '20px'), ('22px', '22px'), ('24px', '24px')], default='16px', max_length=10),
        ),
    ]
