# Generated by Django 5.1 on 2024-08-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingchobo', '0008_alter_pboard_category_alter_pboard_font_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pboard',
            name='font_family',
            field=models.CharField(choices=[('Hahmlet', 'Hahmlet'), ('Orbit', 'Orbit'), ('Dongle', 'Dongle'), ('Jua', 'Jua')], default='Noto Sans KR', max_length=50),
        ),
    ]
