# Generated by Django 5.1 on 2024-08-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingchobo', '0009_alter_pboard_font_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pboard',
            name='font_family',
            field=models.CharField(choices=[('Hahmlet', 'Hahmlet'), ('Orbit', 'Orbit'), ('Dongle', 'Dongle'), ('Jua', 'Jua')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pboard',
            name='font_size',
            field=models.CharField(choices=[('16px', '16px'), ('18px', '18px'), ('20px', '20px'), ('22px', '22px'), ('24px', '24px')], max_length=10),
        ),
    ]
